apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner-scaler
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gitlab-runner-scaler
  template:
    metadata:
      labels:
        app: gitlab-runner-scaler
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532  # Matches distroless:nonroot UID
        runAsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 65532  # Only needed if you mount volumes that need write access
      containers:
        - name: scaler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          env:
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitlab-runner-scaler-secret
                  key: token
            - name: GITLAB_RUNNER_ID
              value: "{{ .Values.gitlab.runnerID }}"
            - name: PENDING_JOBS_PER_RUNNER
              value: "{{ .Values.gitlab.pendingJobsPerRunner }}"
              
