apiVersion: v1
kind: Service
metadata:
  name: gitlab-runner-scaler-service
spec:
  selector:
    app: gitlab-runner-scaler
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
